/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Aurélien Martel (https://sketchfab.com/aurelien_martel)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/exterior-architecture-28c251353946454bb57622cb512bca7e
Title: Exterior Architecture
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/assets/id430/bldgs/bldg.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-4.041, 1.457, 7.225]}>
          <mesh castShadow receiveShadow geometry={nodes.batiment006_0.geometry} material={materials.batiment} />
          <mesh castShadow receiveShadow geometry={nodes.batiment006_1.geometry} material={materials["facade-bois"]} />
        </group>
        <group position={[-4.041, 1.457, 7.225]} scale={[3.205, 2.043, 2.043]}>
          <mesh castShadow receiveShadow geometry={nodes.Cube008_0.geometry} material={materials.batiment} position={[1.617, -1.338, -2.071]} scale={[1.056, 1.657, 1.657]} />
        </group>
        <group position={[-4.041, 1.457, 10.06]}>
          <mesh castShadow receiveShadow geometry={nodes.plancher010_0.geometry} material={materials.batiment} />
          <mesh castShadow receiveShadow geometry={nodes.plancher010_1.geometry} material={materials.rooftop} />
        </group>
        <group position={[0.364, 0.687, 5.491]}>
          <mesh castShadow receiveShadow geometry={nodes.Window001_0.geometry} material={materials.material} />
          <mesh castShadow receiveShadow geometry={nodes.Window001_1.geometry} material={materials.Plastic} />
          <mesh castShadow receiveShadow geometry={nodes.Window001_2.geometry} material={materials.Glass} />
        </group>
        <group position={[2.504, 3.057, 8.306]} rotation={[0, 0, Math.PI / 2]}>
          <mesh castShadow receiveShadow geometry={nodes.Window003_0.geometry} material={materials.material} />
          <mesh castShadow receiveShadow geometry={nodes.Window003_1.geometry} material={materials.Plastic} />
          <mesh castShadow receiveShadow geometry={nodes.Window003_2.geometry} material={materials.Glass} />
        </group>
        <group position={[0.364, 5.117, 8.311]} rotation={[0, 0, -Math.PI]}>
          <mesh castShadow receiveShadow geometry={nodes.Window000_0.geometry} material={materials.material} />
          <mesh castShadow receiveShadow geometry={nodes.Window000_1.geometry} material={materials.Plastic} />
          <mesh castShadow receiveShadow geometry={nodes.Window000_2.geometry} material={materials.Glass} />
        </group>
        <group position={[-1.776, 3.057, 8.306]} rotation={[0, 0, Math.PI / 2]}>
          <mesh castShadow receiveShadow geometry={nodes.Window004_0.geometry} material={materials.material} />
          <mesh castShadow receiveShadow geometry={nodes.Window004_1.geometry} material={materials.Plastic} />
          <mesh castShadow receiveShadow geometry={nodes.Window004_2.geometry} material={materials.Glass} />
        </group>
        <group position={[0.364, 5.14, 10.719]} rotation={[1.472, 0, Math.PI]}>
          <mesh castShadow receiveShadow geometry={nodes.Window002_0.geometry} material={materials.material} />
          <mesh castShadow receiveShadow geometry={nodes.Window002_1.geometry} material={materials.Plastic} />
          <mesh castShadow receiveShadow geometry={nodes.Window002_2.geometry} material={materials.Glass} />
        </group>
        <group position={[5.526, 1.181, 6.501]}>
          <mesh castShadow receiveShadow geometry={nodes.Window005_0.geometry} material={materials.material} />
          <mesh castShadow receiveShadow geometry={nodes.Window005_1.geometry} material={materials.Plastic} />
          <mesh castShadow receiveShadow geometry={nodes.Window005_2.geometry} material={materials.Glass} />
        </group>
        <group position={[6.316, 2.576, 6.501]} rotation={[0, 0, Math.PI / 2]}>
          <mesh castShadow receiveShadow geometry={nodes.Window006_0.geometry} material={materials.material} />
          <mesh castShadow receiveShadow geometry={nodes.Window006_1.geometry} material={materials.Plastic} />
          <mesh castShadow receiveShadow geometry={nodes.Window006_2.geometry} material={materials.Glass} />
        </group>
        <group position={[-6.423, -0.468, 6.69]}>
          <mesh castShadow receiveShadow geometry={nodes.Window007_0.geometry} material={materials.material} />
          <mesh castShadow receiveShadow geometry={nodes.Window007_1.geometry} material={materials.Plastic} />
          <mesh castShadow receiveShadow geometry={nodes.Window007_2.geometry} material={materials.Glass} />
        </group>
        <group position={[-7.098, 0.678, 6.69]} rotation={[0, 0, -Math.PI / 2]}>
          <mesh castShadow receiveShadow geometry={nodes.Window008_0.geometry} material={materials.material} />
          <mesh castShadow receiveShadow geometry={nodes.Window008_1.geometry} material={materials.Plastic} />
          <mesh castShadow receiveShadow geometry={nodes.Window008_2.geometry} material={materials.Glass} />
        </group>
        <group position={[6.316, 7.593, 6.501]} rotation={[0, 0, Math.PI / 2]}>
          <mesh castShadow receiveShadow geometry={nodes.Window009_0.geometry} material={materials.material} />
          <mesh castShadow receiveShadow geometry={nodes.Window009_1.geometry} material={materials.Plastic} />
          <mesh castShadow receiveShadow geometry={nodes.Window009_2.geometry} material={materials.Glass} />
        </group>
        <group position={[2.431, 9.828, 6.501]} rotation={[0, 0, -Math.PI]}>
          <mesh castShadow receiveShadow geometry={nodes.Window010_0.geometry} material={materials.material} />
          <mesh castShadow receiveShadow geometry={nodes.Window010_1.geometry} material={materials.Plastic} />
          <mesh castShadow receiveShadow geometry={nodes.Window010_2.geometry} material={materials.Glass} />
        </group>
        <group position={[-2.059, 8.217, 5.491]} rotation={[0, 0, -Math.PI / 2]}>
          <mesh castShadow receiveShadow geometry={nodes.Window011_0.geometry} material={materials.material} />
          <mesh castShadow receiveShadow geometry={nodes.Window011_1.geometry} material={materials.Plastic} />
          <mesh castShadow receiveShadow geometry={nodes.Window011_2.geometry} material={materials.Glass} />
        </group>
        <group position={[-7.098, 5.037, 5.491]} rotation={[0, 0, -Math.PI / 2]}>
          <mesh castShadow receiveShadow geometry={nodes.Window012_0.geometry} material={materials.material} />
          <mesh castShadow receiveShadow geometry={nodes.Window012_1.geometry} material={materials.Plastic} />
          <mesh castShadow receiveShadow geometry={nodes.Window012_2.geometry} material={materials.Glass} />
        </group>
        <group position={[-7.098, 2.346, 5.491]} rotation={[0, 0, -Math.PI / 2]}>
          <mesh castShadow receiveShadow geometry={nodes.Window013_0.geometry} material={materials.material} />
          <mesh castShadow receiveShadow geometry={nodes.Window013_1.geometry} material={materials.Plastic} />
          <mesh castShadow receiveShadow geometry={nodes.Window013_2.geometry} material={materials.Glass} />
        </group>
        <group position={[-4.662, -0.468, 5.491]}>
          <mesh castShadow receiveShadow geometry={nodes.Window014_0.geometry} material={materials.material} />
          <mesh castShadow receiveShadow geometry={nodes.Window014_1.geometry} material={materials.Plastic} />
          <mesh castShadow receiveShadow geometry={nodes.Window014_2.geometry} material={materials.Glass} />
        </group>
        <group position={[-3.155, -0.468, 5.491]}>
          <mesh castShadow receiveShadow geometry={nodes.Window015_0.geometry} material={materials.material} />
          <mesh castShadow receiveShadow geometry={nodes.Window015_1.geometry} material={materials.Plastic} />
          <mesh castShadow receiveShadow geometry={nodes.Window015_2.geometry} material={materials.Glass} />
        </group>
        <group position={[4.39, -2.028, 3.914]} rotation={[0, 0, Math.PI / 2]}>
          <mesh castShadow receiveShadow geometry={nodes.Window016_0.geometry} material={materials.material} />
          <mesh castShadow receiveShadow geometry={nodes.Window016_1.geometry} material={materials.Plastic} />
          <mesh castShadow receiveShadow geometry={nodes.Window016_2.geometry} material={materials.Glass} />
        </group>
        <group position={[6.316, 8.596, 3.914]} rotation={[0, 0, Math.PI / 2]}>
          <mesh castShadow receiveShadow geometry={nodes.Window017_0.geometry} material={materials.material} />
          <mesh castShadow receiveShadow geometry={nodes.Window017_1.geometry} material={materials.Plastic} />
          <mesh castShadow receiveShadow geometry={nodes.Window017_2.geometry} material={materials.Glass} />
        </group>
        <group position={[6.316, 7.19, 3.914]} rotation={[0, 0, Math.PI / 2]}>
          <mesh castShadow receiveShadow geometry={nodes.Window018_0.geometry} material={materials.material} />
          <mesh castShadow receiveShadow geometry={nodes.Window018_1.geometry} material={materials.Plastic} />
          <mesh castShadow receiveShadow geometry={nodes.Window018_2.geometry} material={materials.Glass} />
        </group>
        <group position={[-2.059, 7.073, 3.914]} rotation={[0, 0, -Math.PI / 2]}>
          <mesh castShadow receiveShadow geometry={nodes.Window019_0.geometry} material={materials.material} />
          <mesh castShadow receiveShadow geometry={nodes.Window019_1.geometry} material={materials.Plastic} />
          <mesh castShadow receiveShadow geometry={nodes.Window019_2.geometry} material={materials.Glass} />
        </group>
        <group position={[-5.048, 4.995, 2.55]} rotation={[0, 0, -Math.PI / 2]}>
          <mesh castShadow receiveShadow geometry={nodes.Window020_0.geometry} material={materials.material} />
          <mesh castShadow receiveShadow geometry={nodes.Window020_1.geometry} material={materials.Plastic} />
          <mesh castShadow receiveShadow geometry={nodes.Window020_2.geometry} material={materials.Glass} />
          <mesh castShadow receiveShadow geometry={nodes.Window020_3.geometry} material={materials.Marble} />
        </group>
        <group position={[-2.106, -0.444, 2.55]} rotation={[0, 0, -Math.PI / 2]}>
          <mesh castShadow receiveShadow geometry={nodes.Window022_0.geometry} material={materials.material} />
          <mesh castShadow receiveShadow geometry={nodes.Window022_1.geometry} material={materials.Plastic} />
          <mesh castShadow receiveShadow geometry={nodes.Window022_2.geometry} material={materials.Glass} />
          <mesh castShadow receiveShadow geometry={nodes.Window022_3.geometry} material={materials.Marble} />
        </group>
        <group position={[-3.551, 0.82, 2.55]}>
          <mesh castShadow receiveShadow geometry={nodes.Window023_0.geometry} material={materials.material} />
          <mesh castShadow receiveShadow geometry={nodes.Window023_1.geometry} material={materials.Plastic} />
          <mesh castShadow receiveShadow geometry={nodes.Window023_2.geometry} material={materials.Glass} />
          <mesh castShadow receiveShadow geometry={nodes.Window023_3.geometry} material={materials.Marble} />
        </group>
        <group position={[-3.544, 6.39, 2.55]}>
          <mesh castShadow receiveShadow geometry={nodes.Window024_0.geometry} material={materials.material} />
          <mesh castShadow receiveShadow geometry={nodes.Window024_1.geometry} material={materials.Plastic} />
          <mesh castShadow receiveShadow geometry={nodes.Window024_2.geometry} material={materials.Glass} />
          <mesh castShadow receiveShadow geometry={nodes.Window024_3.geometry} material={materials.Marble} />
        </group>
        <group position={[-2.113, -3.445, 3.914]} rotation={[0, 0, -Math.PI / 2]}>
          <mesh castShadow receiveShadow geometry={nodes.Window025_0.geometry} material={materials.material} />
          <mesh castShadow receiveShadow geometry={nodes.Window025_1.geometry} material={materials.Plastic} />
          <mesh castShadow receiveShadow geometry={nodes.Window025_2.geometry} material={materials.Glass} />
        </group>
        <group position={[-0.516, -4.59, 3.914]}>
          <mesh castShadow receiveShadow geometry={nodes.Window026_0.geometry} material={materials.material} />
          <mesh castShadow receiveShadow geometry={nodes.Window026_1.geometry} material={materials.Plastic} />
          <mesh castShadow receiveShadow geometry={nodes.Window026_2.geometry} material={materials.Glass} />
        </group>
        <group position={[1.416, 0.885, 1.785]} rotation={[0, 0, -Math.PI]}>
          <mesh castShadow receiveShadow geometry={nodes.Window027_0.geometry} material={materials.material} />
          <mesh castShadow receiveShadow geometry={nodes.Window027_1.geometry} material={materials.Plastic} />
          <mesh castShadow receiveShadow geometry={nodes.Window027_2.geometry} material={materials.Glass} />
        </group>
        <group position={[2.127, -2.721, 1.785]} rotation={[0, 0, Math.PI / 2]}>
          <mesh castShadow receiveShadow geometry={nodes.Window028_0.geometry} material={materials.material} />
          <mesh castShadow receiveShadow geometry={nodes.Window028_1.geometry} material={materials.Plastic} />
          <mesh castShadow receiveShadow geometry={nodes.Window028_2.geometry} material={materials.Glass} />
        </group>
        <group position={[4.401, 2.868, 4.531]} rotation={[0, 0, Math.PI / 2]}>
          <mesh castShadow receiveShadow geometry={nodes.Window029_0.geometry} material={materials.material} />
          <mesh castShadow receiveShadow geometry={nodes.Window029_1.geometry} material={materials.Plastic} />
          <mesh castShadow receiveShadow geometry={nodes.Window029_2.geometry} material={materials.Glass} />
        </group>
        <group position={[-5.048, 2.225, 2.55]} rotation={[0, 0, -Math.PI / 2]}>
          <mesh castShadow receiveShadow geometry={nodes.Window021_0.geometry} material={materials.material} />
          <mesh castShadow receiveShadow geometry={nodes.Window021_1.geometry} material={materials.Plastic} />
          <mesh castShadow receiveShadow geometry={nodes.Window021_2.geometry} material={materials.Glass} />
          <mesh castShadow receiveShadow geometry={nodes.Window021_3.geometry} material={materials.Marble} />
        </group>
        <mesh castShadow receiveShadow geometry={nodes.batiment_0.geometry} material={materials["mur-brique"]} position={[-7.122, -4.285, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.plancher002_0.geometry} material={materials.batiment} position={[0.168, 3.177, 2.385]} />
        <mesh castShadow receiveShadow geometry={nodes["plancher-ss-sol001_0"].geometry} material={materials["plancher-ss-sol"]} position={[0.168, 3.177, -0.245]} />
        <mesh castShadow receiveShadow geometry={nodes["cube-cuisine003_0"].geometry} material={materials.batiment} position={[1.14, -1.337, 2.994]} scale={3.386} />
        <mesh castShadow receiveShadow geometry={nodes.batiment004_0.geometry} material={materials.batiment} position={[4.391, 1.236, 2.681]} scale={0.172} />
        <mesh castShadow receiveShadow geometry={nodes.cloison005_0.geometry} material={materials.Root} position={[4.147, -1.041, 4.521]} scale={0.056} />
        <mesh castShadow receiveShadow geometry={nodes.cloison009_0.geometry} material={materials.Root} position={[-2.642, 1.613, 5.543]} scale={[0.052, 1.752, 0.052]} />
        <mesh castShadow receiveShadow geometry={nodes["cadre-porte011_0"].geometry} material={materials.porte} position={[-1.617, -0.511, 5.491]} />
        <mesh castShadow receiveShadow geometry={nodes.porte012_0.geometry} material={materials.porte} position={[-1.617, -0.511, 5.491]} />
        <mesh castShadow receiveShadow geometry={nodes.poignet_0.geometry} material={materials.poignet} position={[-1.889, -0.511, 6.48]} rotation={[Math.PI / 2, 0, 0]} scale={0.033} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["poignet-ext004_0"].geometry}
          material={materials.poignet}
          position={[4.403, 2.096, 3.499]}
          rotation={[Math.PI / 2, Math.PI / 2, 0]}
          scale={0.033}
        />
        <mesh castShadow receiveShadow geometry={nodes["cadre-porte-garage025_0"].geometry} material={materials["porte-garage"]} position={[-0.63, 0.782, -0.12]} scale={[0.354, 0.023, 1.011]} />
        <mesh castShadow receiveShadow geometry={nodes["garage-rideau026_0"].geometry} material={materials["porte-garage"]} position={[-0.63, 0.763, -0.12]} />
        <mesh castShadow receiveShadow geometry={nodes["porte-garage_0"].geometry} material={materials.poignet} position={[-0.63, 0.763, 0.412]} scale={0.045} />
        <mesh castShadow receiveShadow geometry={nodes["porte-garage001_0"].geometry} material={materials.poignet} position={[-4.464, 0.763, 0.412]} scale={0.045} />
        <mesh castShadow receiveShadow geometry={nodes["garage-rideau027_0"].geometry} material={materials["porte-garage"]} position={[-4.464, 0.763, -0.12]} />
        <mesh castShadow receiveShadow geometry={nodes["cadre-porte-garage_0"].geometry} material={materials["porte-garage"]} position={[-4.464, 0.782, -0.12]} scale={[0.354, 0.023, 1.011]} />
        <mesh castShadow receiveShadow geometry={nodes["pieds-rambarde_0"].geometry} material={materials.rambarde} position={[-2.055, -4.584, 6.548]} scale={[0.013, 0.013, 0.125]} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["rambarde-main001_0"].geometry}
          material={materials.rambarde}
          position={[1.082, -4.584, 6.717]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.013, 0.013, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.rambarde002_0.geometry}
          material={materials.rambarde}
          position={[1.082, -4.584, 6.617]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.004, 0.004, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.rambarde003_0.geometry}
          material={materials.rambarde}
          position={[4.443, -1.282, 6.617]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.004, 0.004, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["rambarde-main004_0"].geometry}
          material={materials.rambarde}
          position={[4.443, -1.282, 6.717]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.013, 0.013, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["pieds-rambarde005_0"].geometry}
          material={materials.rambarde}
          position={[4.443, -4.419, 6.548]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.013, 0.013, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["pieds-rambarde006_0"].geometry}
          material={materials.rambarde}
          position={[-2.167, -4.419, 6.548]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.013, 0.013, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["rambarde-main007_0"].geometry}
          material={materials.rambarde}
          position={[-2.167, -1.282, 6.717]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.013, 0.013, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.rambarde008_0.geometry}
          material={materials.rambarde}
          position={[-2.167, -1.282, 6.617]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.004, 0.004, 0.125]}
        />
        <mesh castShadow receiveShadow geometry={nodes["pieds-rambarde009_0"].geometry} material={materials.rambarde} position={[-7.006, -4.292, 3.562]} scale={[0.013, 0.013, 0.125]} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["rambarde-main010_0"].geometry}
          material={materials.rambarde}
          position={[-3.869, -4.292, 3.731]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.013, 0.013, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.rambarde011_0.geometry}
          material={materials.rambarde}
          position={[-3.869, -4.292, 3.631]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.004, 0.004, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.rambarde012_0.geometry}
          material={materials.rambarde}
          position={[-7.118, -2.423, 3.631]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.004, 0.004, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["rambarde-main013_0"].geometry}
          material={materials.rambarde}
          position={[-7.118, -2.423, 3.731]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.013, 0.013, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["pieds-rambarde014_0"].geometry}
          material={materials.rambarde}
          position={[-7.118, 0.714, 3.562]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.013, 0.013, 0.125]}
        />
        <mesh castShadow receiveShadow geometry={nodes["pieds-rambarde015_0"].geometry} material={materials.rambarde} position={[2.66, 1.254, 9.409]} scale={[0.013, 0.013, 0.125]} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["rambarde-main016_0"].geometry}
          material={materials.rambarde}
          position={[5.797, 1.254, 9.578]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.013, 0.013, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.rambarde017_0.geometry}
          material={materials.rambarde}
          position={[5.797, 1.254, 9.478]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.004, 0.004, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.rambarde018_0.geometry}
          material={materials.rambarde}
          position={[6.25, 4.598, 9.478]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.004, 0.004, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["rambarde-main019_0"].geometry}
          material={materials.rambarde}
          position={[6.25, 4.598, 9.578]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.013, 0.013, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["pieds-rambarde020_0"].geometry}
          material={materials.rambarde}
          position={[6.25, 1.356, 9.409]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.013, 0.013, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.rambarde021_0.geometry}
          material={materials.rambarde}
          position={[-3.825, -0.345, 9.478]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.004, 0.004, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["rambarde-main022_0"].geometry}
          material={materials.rambarde}
          position={[-3.825, -0.345, 9.578]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.013, 0.013, 0.125]}
        />
        <mesh castShadow receiveShadow geometry={nodes["pieds-rambarde023_0"].geometry} material={materials.rambarde} position={[-6.962, -0.345, 9.409]} scale={[0.013, 0.013, 0.125]} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["pieds-rambarde024_0"].geometry}
          material={materials.rambarde}
          position={[-7.078, -0.151, 9.409]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.013, 0.013, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["rambarde-main025_0"].geometry}
          material={materials.rambarde}
          position={[-7.078, 2.986, 9.578]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.013, 0.013, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.rambarde026_0.geometry}
          material={materials.rambarde}
          position={[-7.078, 2.986, 9.478]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.004, 0.004, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.rambarde027_0.geometry}
          material={materials.rambarde}
          position={[-3.753, 7.517, 9.478]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.004, 0.004, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["rambarde-main028_0"].geometry}
          material={materials.rambarde}
          position={[-3.753, 7.517, 9.578]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.013, 0.013, 0.125]}
        />
        <mesh castShadow receiveShadow geometry={nodes["pieds-rambarde029_0"].geometry} material={materials.rambarde} position={[-6.89, 7.517, 9.409]} scale={[0.013, 0.013, 0.125]} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["pieds-rambarde030_0"].geometry}
          material={materials.rambarde}
          position={[-2.055, 7.685, 9.41]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.013, 0.013, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["rambarde-main031_0"].geometry}
          material={materials.rambarde}
          position={[-2.055, 10.097, 9.579]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.013, 0.013, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.rambarde032_0.geometry}
          material={materials.rambarde}
          position={[-2.055, 10.822, 9.479]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.004, 0.004, 0.125]}
        />
        <mesh castShadow receiveShadow geometry={nodes["pieds-rambarde033_0"].geometry} material={materials.rambarde} position={[-1.855, 9.868, 9.409]} scale={[0.013, 0.013, 0.125]} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["rambarde-main034_0"].geometry}
          material={materials.rambarde}
          position={[1.282, 9.868, 9.578]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.013, 0.013, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.rambarde035_0.geometry}
          material={materials.rambarde}
          position={[1.282, 9.868, 9.478]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.004, 0.004, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["pieds-rambarde036_0"].geometry}
          material={materials.rambarde}
          position={[-0.898, -0.179, 9.408]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.013, 0.013, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["rambarde-main037_0"].geometry}
          material={materials.rambarde}
          position={[-0.898, 2.958, 9.578]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.013, 0.013, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.rambarde038_0.geometry}
          material={materials.rambarde}
          position={[-0.898, 2.958, 9.478]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.004, 0.004, 0.125]}
        />
        <mesh castShadow receiveShadow geometry={nodes["palier-ext_0"].geometry} material={materials["sol-exterieur"]} position={[5.426, 2.02, 2.51]} />
        <mesh castShadow receiveShadow geometry={nodes.escalier001_0.geometry} material={materials["marches-escalier1"]} position={[5.438, -4.345, -0.065]} />
        <mesh castShadow receiveShadow geometry={nodes.escalier002_0.geometry} material={materials["marches-escalier1"]} position={[8.355, 4.208, 2.622]} />
        <mesh castShadow receiveShadow geometry={nodes["palier-ext003_0"].geometry} material={materials["sol-exterieur"]} position={[5.426, 2.02, 5.491]} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["pieds-rambarde039_0"].geometry}
          material={materials.rambarde}
          position={[7.416, 9.25, 5.944]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.013, 0.013, 0.406]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["rambarde-main040_0"].geometry}
          material={materials.rambarde}
          position={[7.416, 12.442, 6.468]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.013, 0.013, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.rambarde041_0.geometry}
          material={materials.rambarde}
          position={[7.416, 12.442, 6.316]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.004, 0.004, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.rambarde042_0.geometry}
          material={materials.rambarde}
          position={[4.033, 10.936, 6.316]}
          rotation={[Math.PI, -Math.PI / 2, 0]}
          scale={[0.004, 0.004, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["rambarde-main043_0"].geometry}
          material={materials.rambarde}
          position={[4.033, 10.936, 6.468]}
          rotation={[Math.PI, -Math.PI / 2, 0]}
          scale={[0.013, 0.013, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["pieds-rambarde044_0"].geometry}
          material={materials.rambarde}
          position={[7.225, 10.936, 5.944]}
          rotation={[0, 0, -Math.PI]}
          scale={[0.013, 0.013, 0.406]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["pieds-rambarde045_0"].geometry}
          material={materials.rambarde}
          position={[3.28, 10.996, 5.944]}
          rotation={[0, 0, -Math.PI]}
          scale={[0.013, 0.013, 0.406]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["rambarde-main046_0"].geometry}
          material={materials.rambarde}
          position={[0.088, 10.996, 6.468]}
          rotation={[Math.PI, -Math.PI / 2, 0]}
          scale={[0.013, 0.013, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.rambarde047_0.geometry}
          material={materials.rambarde}
          position={[0.088, 10.996, 6.316]}
          rotation={[Math.PI, -Math.PI / 2, 0]}
          scale={[0.004, 0.004, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.rambarde048_0.geometry}
          material={materials.rambarde}
          position={[4.23, 8.465, 6.316]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.004, 0.004, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["rambarde-main049_0"].geometry}
          material={materials.rambarde}
          position={[4.23, 8.465, 6.468]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.013, 0.013, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["pieds-rambarde050_0"].geometry}
          material={materials.rambarde}
          position={[4.229, 10.873, 5.944]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.013, 0.013, 0.406]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["pieds-rambarde051_0"].geometry}
          material={materials.rambarde}
          position={[3.441, 10.873, 5.821]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.013, 0.013, 0.295]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["rambarde-main052_0"].geometry}
          material={materials.rambarde}
          position={[3.442, 8.465, 6.468]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.013, 0.013, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.rambarde053_0.geometry}
          material={materials.rambarde}
          position={[3.442, 8.465, 6.316]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.004, 0.004, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.rambarde054_0.geometry}
          material={materials.rambarde}
          position={[1.433, 8.465, 6.316]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.004, 0.004, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["rambarde-main055_0"].geometry}
          material={materials.rambarde}
          position={[1.433, 8.465, 6.468]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.013, 0.013, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["pieds-rambarde056_0"].geometry}
          material={materials.rambarde}
          position={[1.432, 10.873, 5.944]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.013, 0.013, 0.406]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["pieds-rambarde057_0"].geometry}
          material={materials.rambarde}
          position={[7.416, 4.408, 3.179]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.013, 0.013, 0.406]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.rambarde058_0.geometry}
          material={materials.rambarde}
          position={[7.417, 4.717, 3.919]}
          rotation={[-1.081, 0.001, 1.57]}
          scale={[0.004, 0.004, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["rambarde-main059_0"].geometry}
          material={materials.rambarde}
          position={[7.417, 4.692, 4.003]}
          rotation={[-1.065, 0, 1.571]}
          scale={[0.013, 0.013, 0.125]}
        />
        <mesh castShadow receiveShadow geometry={nodes["Sol-environnement004_0"].geometry} material={materials["sol-environ"]} position={[0, 0, -0.168]} />
        <mesh castShadow receiveShadow geometry={nodes.plancher003_0.geometry} material={materials.Root} position={[-4.041, 1.457, 7.225]} scale={[3.205, 2.043, 2.043]} />
        <mesh castShadow receiveShadow geometry={nodes.escalier000_0.geometry} material={materials.Root} position={[2.819, 2.049, 5.597]} />
        <mesh castShadow receiveShadow geometry={nodes.Plane_0.geometry} material={materials.Root} position={[2.758, 2.049, 5.548]} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["rambarde-main000_0"].geometry}
          material={materials.Root}
          position={[2.489, 2.036, 6.565]}
          rotation={[-0.71, 0, 1.571]}
          scale={[0.013, 0.013, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["pieds-rambarde001_0"].geometry}
          material={materials.Root}
          position={[2.49, 2.112, 5.971]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.007, 0.007, 0.406]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["pieds-rambarde002_0"].geometry}
          material={materials.Root}
          position={[1.829, 2.112, 5.971]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.007, 0.007, 0.406]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["rambarde-main002_0"].geometry}
          material={materials.Root}
          position={[1.828, 2.036, 6.565]}
          rotation={[-0.71, 0, 1.571]}
          scale={[0.013, 0.013, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["rambarde-main003_0"].geometry}
          material={materials.Root}
          position={[1.828, 2.007, 3.749]}
          rotation={[-0.71, 0, 1.571]}
          scale={[0.013, 0.013, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["pieds-rambarde003_0"].geometry}
          material={materials.Root}
          position={[1.829, 2.112, 3.202]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.007, 0.007, 0.406]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["pieds-rambarde004_0"].geometry}
          material={materials.Root}
          position={[2.509, 2.112, 3.202]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.007, 0.007, 0.406]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["rambarde-main005_0"].geometry}
          material={materials.Root}
          position={[2.508, 2.007, 3.749]}
          rotation={[-0.71, 0, 1.571]}
          scale={[0.013, 0.013, 0.125]}
        />
        <mesh castShadow receiveShadow geometry={nodes.Plane001_0.geometry} material={materials.Root} position={[2.779, 2.049, 2.721]} />
        <mesh castShadow receiveShadow geometry={nodes.escalier003_0.geometry} material={materials.Root} position={[2.819, 2.109, 2.771]} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["pieds-rambarde007_0"].geometry}
          material={materials.Root}
          position={[0.951, 4.535, 8.762]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.007, 0.007, 0.406]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["rambarde-main006_0"].geometry}
          material={materials.Root}
          position={[-1.693, 4.536, 9.437]}
          rotation={[Math.PI, -Math.PI / 2, 0]}
          scale={[0.013, 0.013, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["rambarde-main008_0"].geometry}
          material={materials.Root}
          position={[-1.693, 4.058, 6.62]}
          rotation={[Math.PI, -Math.PI / 2, 0]}
          scale={[0.013, 0.013, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["pieds-rambarde008_0"].geometry}
          material={materials.Root}
          position={[1.709, 4.058, 5.946]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.007, 0.007, 0.406]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["pieds-rambarde010_0"].geometry}
          material={materials.Root}
          position={[-1.135, 3.977, 5.946]}
          rotation={[0, 0, -Math.PI]}
          scale={[0.007, 0.007, 0.406]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["rambarde-main009_0"].geometry}
          material={materials.Root}
          position={[-1.135, 0.575, 6.62]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.013, 0.013, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["rambarde-main011_0"].geometry}
          material={materials.Root}
          position={[2.615, 0.983, 6.62]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.013, 0.013, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["pieds-rambarde011_0"].geometry}
          material={materials.Root}
          position={[2.615, 4.385, 5.946]}
          rotation={[0, 0, -Math.PI]}
          scale={[0.007, 0.007, 0.406]}
        />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder_0.geometry} material={materials.pilier} position={[6.285, 1.203, 2.51]} scale={[0.053, 0.053, 1]} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder001_0.geometry} material={materials.pilier} position={[-6.892, -0.448, 2.51]} scale={[0.053, 0.053, 1]} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder002_0.geometry} material={materials.pilier} position={[-6.892, 7.352, 2.51]} scale={[0.053, 0.053, 1]} />
        <mesh castShadow receiveShadow geometry={nodes.batiment002_0.geometry} material={materials.batiment} position={[-7.122, -4.285, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.poignet001_0.geometry} material={materials.poignet} position={[3.494, 1.092, 6.48]} rotation={[Math.PI / 2, 0, 0]} scale={0.033} />
        <mesh castShadow receiveShadow geometry={nodes.porte000_0.geometry} material={materials.porte} position={[3.767, 1.092, 5.491]} />
        <mesh castShadow receiveShadow geometry={nodes["cadre-porte000_0"].geometry} material={materials.porte} position={[3.767, 1.092, 5.491]} />
        <mesh castShadow receiveShadow geometry={nodes["cadre-porte001_0"].geometry} material={materials.porte} position={[3.836, 9.901, 5.491]} scale={[-1, 1, 1]} />
        <mesh castShadow receiveShadow geometry={nodes.porte001_0.geometry} material={materials.porte} position={[3.836, 9.901, 5.491]} scale={[-1, 1, 1]} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.poignet002_0.geometry}
          material={materials.poignet}
          position={[4.108, 9.901, 6.48]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[-0.033, 0.033, 0.033]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.poignet003_0.geometry}
          material={materials.poignet}
          position={[1.301, 9.901, 6.48]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[-0.033, 0.033, 0.033]}
        />
        <mesh castShadow receiveShadow geometry={nodes.porte002_0.geometry} material={materials.porte} position={[1.029, 9.901, 5.491]} scale={[-1, 1, 1]} />
        <mesh castShadow receiveShadow geometry={nodes["cadre-porte002_0"].geometry} material={materials.porte} position={[1.029, 9.901, 5.491]} scale={[-1, 1, 1]} />
        <mesh castShadow receiveShadow geometry={nodes.poignet004_0.geometry} material={materials.poignet} position={[1.143, 0.873, 0.869]} rotation={[Math.PI / 2, 0, 0]} scale={0.033} />
        <mesh castShadow receiveShadow geometry={nodes.porte003_0.geometry} material={materials.porte} position={[1.415, 0.873, -0.12]} />
        <mesh castShadow receiveShadow geometry={nodes["cadre-porte003_0"].geometry} material={materials.porte} position={[1.415, 0.873, -0.12]} />
        <mesh castShadow receiveShadow geometry={nodes["cadre-porte004_0"].geometry} material={materials.porte} position={[2.125, -2.72, -0.12]} rotation={[0, 0, Math.PI / 2]} />
        <mesh castShadow receiveShadow geometry={nodes.porte004_0.geometry} material={materials.porte} position={[2.125, -2.72, -0.12]} rotation={[0, 0, Math.PI / 2]} />
        <mesh castShadow receiveShadow geometry={nodes.poignet005_0.geometry} material={materials.poignet} position={[2.125, -3.044, 0.869]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.033} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.poignet006_0.geometry}
          material={materials.poignet}
          position={[2.125, -3.182, 0.869]}
          rotation={[Math.PI / 2, Math.PI / 2, 0]}
          scale={[-0.033, 0.033, 0.033]}
        />
        <mesh castShadow receiveShadow geometry={nodes["cadre-porte005_0"].geometry} material={materials.porte} position={[4.403, 2.368, 2.51]} rotation={[0, 0, Math.PI / 2]} />
        <mesh castShadow receiveShadow geometry={nodes.porte005_0.geometry} material={materials.porte} position={[4.403, 2.368, 2.51]} rotation={[0, 0, Math.PI / 2]} />
        <mesh castShadow receiveShadow geometry={nodes.poignet007_0.geometry} material={materials.poignet} position={[4.403, 2.096, 3.499]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.033} />
      </group>
    </group>
  );
}

useGLTF.preload("/bldg.glb");
